name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: get goblin
      run: go get github.com/franela/goblin

    - name: get go2xunit, for xml report
      run: go get github.com/tebeka/go2xunit
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... | go2xunit > report.xml
    - if: ${{success()}}
      name: Display Test Result
      run: cat report.xml
